### ISSUE TITLE
Disable space transition animation

### ISSUE THREAD

**Issue by AxelPrieto** [mikkelricky/grid-spaces#1]
If you could add a "Disable space transition animation" option, I'd be eternally grateful. We used to have this with TotalSpaces2, but after upgrading to MacOS 12.1 (Monterrey) is no longer anymore. I really need those annoying animation effects to go away :(

**Comment by rimi-itk** [comment]
There are no animations when using `yabai` to switch between spaces. Try running 

```sh
yabai --message space --focus next
```

to check that you can actually switch to, i.e. focus, another space – and that no animation is played.

Make sure that you disable all keyboard shortcuts for moving left/right between spaces in Preferences

<img width="780" alt="Screen Shot 2022-01-13 at 12 12 15" src="https://user-images.githubusercontent.com/11267554/149320237-c2b74dfb-208a-4512-96dd-1465fb7dc99c.png">

and use only `skhd` to switch between spaces via the `navigate` script (cf. https://github.com/mikkelricky/grid-spaces#installation)

**Comment by rimi-itk** [comment]
Please see https://github.com/mikkelricky/grid-spaces#system-preferences for details on how to set your System Preferences.
